### ISSUE TITLE
regex in Mailto.php forbids generic TLD

### ISSUE THREAD

**Issue by ralfwiederhold** [LearningLocker/StatementFactory#8]
The regex only allows TLD that are 2 to 4 characters long and effectively locks out any user from using learninglocker if his email address is based on a generic TLD like ".horse".

**Comment by ht2** [comment]
Hi @ralfwiederhold, that's a good shout. We've certainly never come up against longer TLDs in production environments, but it's just a matter of time until .horse comes a clopping. @ryansmith94 any thoughts? Is it just a matter of removing the char length restrictions on that part of the regex?

The pattern in question:
```
protected static $pattern = '/^mailto:[A-Z0-9.\'_%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i';
```
https://github.com/LearningLocker/StatementFactory/blob/5cf125aa350f91de6bc4677977fd32b34d4b9967/src/Mailto.php#L4

**Comment by ht2** [comment]
I believe that looking at this stackoverflow: http://stackoverflow.com/questions/9238640/how-long-can-a-tld-possibly-be
and this RFC: https://tools.ietf.org/html/rfc1034 (see 3.1 Name space specifications and terminology)
..that the maximum length is CURRENTLY 63 characters.

**Comment by ryansmith94** [comment]
Yeah, that is a great shout.


Haha 10/10 @ht2.
> .horse comes a clopping

We'd definitely have to remove the char length restrictions, and I'm also wondering if it's actually possibly to have an email address on the TLD like james@com, in which case we'd have to make first part optional. In that case I think the following works.

```php
protected static $pattern = '/^mailto:[A-Z0-9.\'_%+-]+@([A-Z0-9.-]+)?\.[A-Z]{1,63}$/i';
```

But if that's not the case, we should be ok with the following instead.

```php
protected static $pattern = '/^mailto:[A-Z0-9.\'_%+-]+@[A-Z0-9.-]+\.[A-Z]{1,63}$/i';
```

Both of those snippets assume that it is limited to 63 characters @ht2.

**Comment by ralfwiederhold** [comment]
Check it out: http://dord.horse/ :)

Though I haven't met another one in the wild yet. But we will definitely encounter some type of communal TLD like .CITY-TLD or .STATE-TLD at some point in our current project. 

I would assume that you will not encounter email-addresses registered directly on a TLD even if it may be possible. I would simply adjust the TLD length limit in the regex. But that's just my 2 cents.

**Comment by ryansmith94** [comment]
Ok, so assuming the code I wrote works, let's go with the following code for now. If someone raises an issue about email addresses registered directly on a TLD we can easily cross that bridge when we get to it @ht2. Thanks for raising the issue @ralfwiederhold :+1: 

```php
protected static $pattern = '/^mailto:[A-Z0-9.\'_%+-]+@[A-Z0-9.-]+\.[A-Z]{1,63}$/i';
```

**Comment by ralfwiederhold** [comment]
Thank you, @ryansmith94 and @ht2
